name: Entrega continua

on:
  workflow_call:

jobs:

  ECS:
    runs-on: ubuntu-latest
    steps:
    - name: Configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        
    - name: Obtendo arquivo da tarefa
      run: aws ecs describe-task-definition --task-definition Tarefa_API-Go1 --query taskDefinition > task-definition.json

    - name: Copia do task definition
      run: cp task-definition.json task-definition.json.old

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: Go
        image: williamliberos/go_ci:${{github.run_number}}
        environment_variables: | 
          HOST=api-go-dev.cj4yk0oyyjzi.us-east-2.rds.amazonaws.com
          USER=postgres
          PASSWORD=123456789
          DBNAME=root
          DBPORT=5432
          PORT=8000

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: Servico-api-go3
        cluster: API-Go
        wait-for-service-stability: true

    - name: Requisicao
      continue-on-error: true
      run: sleep 30s ; wget LB-API-Go-2-2125482094.us-east-2.elb.amazonaws.com:8000/bruno

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: task-definition.json.old
        service: Servico-api-go3
        cluster: API-Go
        wait-for-service-stability: true
